@startuml

title __TENTHOUSANDSSTEPS's Class Diagram__\n

  package org.TenThousandsSteps {
    class Coin {
        ~ value : double
        ~ qtyCoins : int
        ~ Coin()
    }
  }
  

  package org.TenThousandsSteps {
    class Main {
        {static} + main()
    }
  }
  

  package org.TenThousandsSteps {
    class Menu {
        {static} - GREEN : String
        {static} - BLUE : String
        {static} - PASS : String
        {static} - initialPrice : double
        {static} ~ crisps : Product
        {static} ~ mars : Product
        {static} ~ coca : Product
        {static} ~ eugenia : Product
        {static} ~ water : Product
        {static} ~ onePound : Coin
        {static} ~ halfPound : Coin
        {static} ~ twentyPence : Coin
        {static} ~ tenPence : Coin
        {static} ~ fivePence : Coin
        {static} ~ mainMenu()
        {static} - login()
        {static} - adminMenu()
        {static} - checkMaxOrder()
        {static} - insertCoin()
        {static} - subMenu()
        {static} - calculateProfit()
        {static} ~ goBack()
        {static} + clearScreen()
    }
  }
  

  package org.TenThousandsSteps {
    class Pool {
        {static} - GREEN : String
        {static} - onePoundPool : double
        {static} - halfPoundPool : double
        {static} - twentyPencePool : double
        {static} - tenPencePool : double
        {static} - fivePencePool : double
        {static} - totalPool : double
        {static} - clientPool : double
        {static} ~ depositInPool()
        {static} ~ giveChange()
        {static} ~ getTotalPool()
        {static} ~ getClientPool()
        {static} ~ setClientPool()
    }
  }
  

  package org.TenThousandsSteps {
    class Product {
        ~ name : String
        ~ price : double
        ~ qty : int
        ~ Product()
        {static} ~ withdrawProduct()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
